// This file is automatically generated. Do not modify.

package test

type UserProfile struct {
	Uid int32 `thrift:"1,required" json:"uid"`
	Name string `thrift:"2,required" json:"name"`
	Blurb string `thrift:"3,required" json:"blurb"`
}

type RPCClient interface {
	Call(method string, request interface{}, response interface{}) error
}

type UserStorage interface {
	Store(User *UserProfile) (bool, error)
}

type UserStorageServer struct {
	Implementation UserStorage
}

func (s *UserStorageServer) Store(req *UserStorageStoreRequest, res *UserStorageStoreResponse) error {
	val, err := s.Implementation.Store(req.User)
	switch e := err.(type) {
	}
	res.Value = val
	return err
}

type UserStorageStoreRequest struct {
	User *UserProfile `thrift:"1,required" json:"user"`
}

type UserStorageStoreResponse struct {
	Value bool `thrift:"0,required" json:"value"`
}

type UserStorageClient struct {
	Client RPCClient
}

func (s *UserStorageClient) Store(User *UserProfile) (bool, error) {
	req := &UserStorageStoreRequest{
		User: User,
	}
	res := &UserStorageStoreResponse{}
	err := s.Client.Call("store", req, res)
	return res.Value, err
}
